#!/bin/bash

SOCKIN=50505

if [ -z "$1" ]; then
    echo "$0: no input given!"
elif [ ${#1} = 1 ]; then
    echo "$0: command '$1'"
    if [ $(ps -ef|grep " macplayer "|wc -l) = 1 ]; then
       echo "$0: macplayer not running, not sending command!"
    else
        echo -n "$1"|socat - udp-sendto:127.0.0.1:$SOCKIN
    fi
fi
